---
- name: Export kubernetes version variable
  ansible.builtin.set_fact:
    k8s_version: "1.29"

- name: Env version
  command: echo "VERSION={{ k8s_version }}" >> /etc/environment
  become: true

- name: containerd installation
  ansible.builtin.package:
    name:
      - containerd
  become: true  

- name: Configure containerd
  command: |
    mkdir -p /etc/containerd  
  become: true 

- name: Generate default containerd configuration file
  command: containerd config default > /etc/containerd/config.toml
  become: true  

- name: Restart containerd  
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
  become: true  

- name: Download Kubernetes apt repository key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring
    mode: '0644'
  become: true

- name: Convert Release.key to gpg keyring
  command: |
     gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Add Kubernetes apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
  become: true

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Kubernetes packages
  ansible.builtin.package:
    name: 
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes    
  become: true

- name: Enable and start kubelet service
  ansible.builtin.service: 
    name: kubelet
    enabled: true
    state: started
  become: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

# tasks file for k8s-init
- name: Check if Kubernetes has already been initialized
  ansible.builtin.stat:
    path: /etc/k8s_initialized
  register: k8s_init_flag

- name: Initialize Kubernetes
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: not k8s_init_flag.stat.exists

- name: Mark Kubernetes initialization as completed
  ansible.builtin.file:
    name: /etc/k8s_initialized
    state: touch
  when: not k8s_init_flag.stat.exists

- name: Create .kube directory
  ansible.builtin.file:
    name: /root/.kube
    state: directory
    mode: '0755' 
  become: true

- name: Copy admin.conf to .kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: '0644'
  become: true  

# - name: Taint master node to allow scheduling pods
#   ansible.builtin.shell: |
#     'kubectl taint nodes --all node-role.kubernetes.io/master-' 
#   become: true

- name: Get join command for worker nodes
  command: 
    cmd: kubeadm token create --print-join-command
  register: join_command
  become: true
- name: Save join command to file
  ansible.builtin.copy:
    content: "{{ join_command.stdout }}"
    dest: /join-command.sh
    mode: '0755'
  become: true  

- name: Display join command
  ansible.builtin.debug:
    msg: "Use the following command to join worker nodes to the cluster: {{ join_command.stdout }}" 
  become: false



